### ISSUE TITLE
add support for clickable links

### ISSUE THREAD

**Issue by fs111** [DCsunset/taskwarrior-webui#10]
I just discovered your project and I like what I am seeing!

I use taskwarrior in a software dev setup and add JIRA links to the description of tasks. It would be great if your frontend could detect links and make them clickable by default, so that I can look into JIRA for a given task, if I have to.

**Comment by fs111** [comment]
Yeah, they are just regular old links. I think making all links clickable is a great idea.

**Comment by DCsunset** [comment]
Hello, I have added this feature. Links should be clickable in the latest version.

**Comment by fs111** [comment]
@DCsunset  great. Thank you!
