### ISSUE TITLE
Consider adding armv7 docker configuration

### ISSUE THREAD

**Issue by bergercookie** [DCsunset/taskwarrior-webui#16]
It would be nice to also offer docker images for arm platforms.
I wanted to launch this server on my raspberry pi and serve it on my local network so that I can potentially access my tasks via my phone when connected to the same network.

Currently this isn't possible because the docker registry only has amd64 images.

**Comment by DCsunset** [comment]
Hello, I have changed the build workflow to GitHub actions. It is now able to build the armv7 and arm64 docker images.
Feel free to reopen it if there's any problem.

**Comment by matthiascarlier** [comment]
This does not seem to work. 

When I run the container on my raspberry pi, I get a 502 (bad gateway) error. When I run the docker container without detached mode, I get the following error:

```
m@pi:~ $ docker run -p 8081:80 --name taskwarrior-webui -v $HOME/test/.taskrc:/.

taskrc -v $HOME/test/.task:/.task dcsunset/taskwarrior-webui                                  
                                                                                              
                                                                                              
#                                                                                             
# Fatal error in , line 0                                                                     
# unreachable code                                                                            
#                                                                                             
#                                                                                             
#                                                                                             
#FailureMessage Object: 0xffb3d5dc
```
