### ISSUE TITLE
GET /api/tasks error when running with docker container (amd64)

### ISSUE THREAD

**Issue by bergercookie** [DCsunset/taskwarrior-webui#17]
After `docker-run`-ing the container and pointing it to my .taskrc and .task file and directory respectively, and after navigating to localhost:8080, the tasks view is empty and  I can see the folowing error when I open the developer tools:

`GET http://localhost:8080/api/tasks [HTTP/1.1 400 Bad Request 0ms]`

The full error in firefox is as follows:

```
uncaught (in promise) Error: Request failed with status code 400
    NuxtJS 35
        exports
        exports
        onreadystatechange
        exports
        exports
        exports
        promise callback*h.prototype.request
        t
        exports
        <anonymous>
        n
        v
        _invoke
        $/</<
        r
        l
        o
        o
        fetchTasks
        O
        dispatch
        dispatch
        setup
        setup
        data
        kt
        data
        data
        _data
        jn
        jn
        _init
        f
        componentInstance
        init
c713f9e.js:2:168229
    NuxtJS 31
        dispatch
        (Async: promise callback)
    dispatch
        dispatch
        dispatch
        setup
        setup
        data
        kt
        data
        data
        _data
        jn
        jn
        _init
        f
        componentInstance
        init
        n
        v
        v
        Co
        _update
        r
        get
        En
        mount
        $mount
        init
        v
        v
        Co
```

Doing the same via curl, leads to:

```sh
$ curl  http://localhost:8080/api/tasks
Task command error⏎
```

Locally I'm using taskwarrior 2.5.3 to manage my `.task` and `.taskrc` files

**Comment by DCsunset** [comment]
Hello, thanks for your feedback. It seems there's something wrong with the nginx config. I have fixed it in the latest commit. You can check if it works now.

**Comment by DCsunset** [comment]
It has been generated and you can try the latest version now.

**Comment by volodymyrss** [comment]
Sorry to say, I have the same error. Running the export (inside the container as well as on the host) passes well.
Thanks for your work!

**Comment by volodymyrss** [comment]
I found that in my case it was because of many tasks. My case can be resolved by https://github.com/DCsunset/taskwarrior-lib/pull/1

**Comment by DCsunset** [comment]
I have updated `taskwarrior-lib` to the latest version. It should already fix this issue.

**Comment by volodymyrss** [comment]
I just want to comment that I am not completely sure that the problem of @bergercookie if is the same as mine. 
The error message is quite generic and could mean different things, as I realized after my investigation. But it would be great if it also helped @bergercookie !
