### ISSUE TITLE
Inoperable on mobile Safari and mobile Firefox on iOS

### ISSUE THREAD

**Issue by ethereal-engineer** [DCsunset/taskwarrior-webui#21]
Here's what happens if you try to load this on your iPhone
![IMG_9603](https://user-images.githubusercontent.com/2148403/151311803-a6f980ac-fa7e-438d-86f1-4c4cb6005277.PNG)
It just spins. Nothing happens. Works great on Firefox on my linux machines and Mac laptop.

**Comment by DCsunset** [comment]
I think this is the same bug mentioned in #20. It seems that some dependencies cause this problem but I'm not sure whether the recent commits fix them. You can try the latest version and see if it still occurs.

**Comment by ethereal-engineer** [comment]
Is there a docker image tag for the latest release?

**Comment by DCsunset** [comment]
You can update image with the tag `latest` or use the new tag `20220208`. They are the same images.

**Comment by ethereal-engineer** [comment]
Thank you!

**Comment by JoshMock** [comment]
This is still happening for me on iOS 16, both Safari and Firefox. I pulled down `latest` yesterday so it should have any of the dependency upgrades you mentioned in #20. 

Fantastic tool otherwise. Works flawlessly with taskserver on desktop Firefox. Thanks for building it!

**Comment by super-ben** [comment]
Unfortunately, the problem still persists even in the latest version and the latest iOS. This is sad as my main use (90%+) would be iOS devices so at the moment I can’t actively deploy your otherwise fantastic solution.

**Comment by super-ben** [comment]
If it helps in any way, I found this when opening the site in Safari, MacOS:

ChunkLoadError: Loading chunk 2 failed.
(missing: http://hostname:port/_nuxt/cf3ecde.js)

Also:

cf3ecde.js
Line 2 invalid regular expression: invalid group specifier name

This tells me that the problem may be more easily solved by setting up that regular expression differently.

**Comment by JoshMock** [comment]
It’d probably be easier to debug in an unminified JS bundle. I‘ll try to hop on a Mac soon and see if I can reproduce it in Safari. I tried setting up an iOS debugging session on my Linux desktop the other day using [this](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit) but had trouble setting it up.

**Comment by JoshMock** [comment]
Opened https://github.com/DCsunset/taskwarrior-webui/pull/48 to fix this cc @DCsunset.

**Comment by JoshMock** [comment]
Hmm. Still happening after pulling the latest image and running from scratch. Can’t tell if my PR just didn’t fix it, if a service worker is caching old stuff, or if it’s an issue with the image building an outdated copy of the JS somehow.

I’ll keep debugging, but @DCsunset please reopen in the meantime.

**Comment by JoshMock** [comment]
It appears to be a Docker image issue:

This works in Safari:

```bash
cd path/to/repo
docker build -t tw-webui .
docker run -p 50505:80 -v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task tw-webui:latest
```

This does not:

```bash
docker pull dcsunset/taskwarrior-webui:latest
docker run -p 50505:80 -v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task dcsunset/taskwarrior-webui:latest
```

The fact that the second one fails on a JS file `cf3ecde.js` is a strong clue: JS bundle file names change when their contents change, and `latest` still serves the same list of JS file names.

Not sure if you just need to re-run that `docker push` Github action or if something is wrong with the way it's configured that made it build and push old code. :thinking:

**Comment by DCsunset** [comment]
It seems that two workflows were run at the same time yesterday. Maybe the earlier build overwrote the second one. I'll try rebuilding it again.

**Comment by DCsunset** [comment]
In the latest build, the file `cf3ecde.js` doesn't exist anymore. Would you mind testing whether it works now @JoshMock ?

**Comment by JoshMock** [comment]
Yep, it's working! Thanks for rebuilding @DCsunset. :black_heart: 

I might open an issue for some responsive UI improvements now that I can see it on iOS. :laughing:

**Comment by DCsunset** [comment]
That's great! Closing this issue now :D
