### ISSUE TITLE
Task with "wait" isn't hidden

### ISSUE THREAD

**Issue by Paraidomat** [DCsunset/taskwarrior-webui#29]
I've created a Task today (2022-02-15) with a due date of 2022-03-31 and a wait date of 2022-03-01, but the Task isn't hidden or added to the waiting list.

![image](https://user-images.githubusercontent.com/15010683/154047053-87eb1610-d4b4-4662-9b75-f7d17f494f7a.png)

![image](https://user-images.githubusercontent.com/15010683/154047130-52df8876-9ef2-49da-9289-ca10e5fd94fc.png)

Am I doing something wrong?

**Comment by DCsunset** [comment]
It seems that since taskwarrior v2.6, `waiting` status has been removed. I'll try to fix this issue when I have time.

**Comment by Paraidomat** [comment]
Just for reference: https://github.com/GothenburgBitFactory/taskwarrior/issues/2554

**Comment by DCsunset** [comment]
I've fixed this bug in the latest commit. You can try the latest docker image.

**Comment by Paraidomat** [comment]
works, thanks!
