### ISSUE TITLE
Taskserver support?

### ISSUE THREAD

**Issue by funroompc** [DCsunset/taskwarrior-webui#3]
Hi, came across this and it’s exactly what I’ve been looking for! Thank you for your great work!

If I understand correctly, this works great on a local install of taskwarrior. I use taskserver in a separate container.

Is there anyway in which I can sync this to taskserver?

**Comment by DCsunset** [comment]
Hello, thanks for your advice.

It currently works without a taskserver, because the task directory could be placed either locally or remotely. But it also sounds reasonable to add the synchronization for the taskserver. Maybe I could add a setting to periodically sync to the server by running `task sync` in the future.

**Comment by funroompc** [comment]
Hi,
Thank you for your reply.

I’m trying to think of a way in which I can use this with a taskserver. I will post here if I find a workaround

Looking forward to further development!

Thanks!

**Comment by DCsunset** [comment]
Hello, I have added support for taskserver in the latest version. You could find it in the settings of Web UI.
The FAQ section describes how to prepare for the automatic sync.

I hope the new version could help resolve this issue.

**Comment by funroompc** [comment]
Hey there,

Just wanted to let you know that I will be upgrading the container this week and am looking forward to testing the changes soon :) I have been busy upgrading my setup and am currently in the process of reimplementing my task setup.

Thanks for the update!

**Comment by DCsunset** [comment]
Feel free to open an issue if there's something wrong or unclear :)
