### ISSUE TITLE
Set time zone on backend

### ISSUE THREAD

**Issue by ShizuhaAki** [DCsunset/taskwarrior-webui#34]
I'm trying to set the time zone in the docker container with this:

```shell
date -s "$(date -Iseconds | sed "s/\\+[0-9\:]+//g;s/T/ /g;s/14/22/g" -r)"
```

But it denied me permission to do so. How to properly configure the time zone?

Using `export TZ=Asia/Shanghai` also failed.

**Comment by DCsunset** [comment]
I think you can try setting the environment variable when creating the container instead of changing it at runtime.

For example, you can use the `-e` option in docker command:

```
docker run -e TZ=Asia/Shanghai -d -p 8080:80 --name taskwarrior-webui \
	-v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task \
	dcsunset/taskwarrior-webui
```

Feel free to comment here if it doesn't work for you.

**Comment by DCsunset** [comment]
Closing it due to inactivity.
