### ISSUE TITLE
Add "annotation" feature

### ISSUE THREAD

**Issue by Paraidomat** [DCsunset/taskwarrior-webui#35]
Hi,

are there any plans to add the annotation feature to taskwarrior-webui?

See here: [taskwarrior docs](https://taskwarrior.org/docs/terminology.html#annotation)

**Comment by DCsunset** [comment]
Hello, thanks for your interest. I'm pretty busy recently and may not have the time to do it.

Any PR is welcome if you or anyone is interested in implementing this feature.

**Comment by DCsunset** [comment]
@Paraidomat The support for annotations has been added by #38. You can try the latest version.

**Comment by Paraidomat** [comment]
Works like a charm.

Thank you very much @flaktack :)
