### ISSUE TITLE
Docker image looking for .taskrc in /root instead of /

### ISSUE THREAD

**Issue by n8willis** [DCsunset/taskwarrior-webui#45]
This may be entirely me not grasping something about the docker side of things, of which I'm only an occasional user, but here goes....

I tried to set up the docker image to work with an (external) taskserver instance. Which meant that I needed to edit/configure the .taskrc file and then get the docker image to use it.

The `task` binary in the image seems to be looking for its configuration in `/root`, rather than in `/` (where the `-v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task` switch puts them....).

Thus it doesn't sync, and if you try other `task` subcommands via docker exec, those don't work either. It just gives you 
```
A configuration file could not be found in /root

Would you like a sample /root/.taskrc created, so Taskwarrior can proceed? (yes/no) Cannot proceed without rc file.
```

So, is that just a case of "the example `docker run` command in the README needs updating"? Or some environment variable getting in the way? Or am I missing something obvious here (I did run the docker-run command as-written just to be sure)?

Seems like a small enough difference that it should be a quick fix; I'm just not certain what, and maybe nobody else has started off with a pre-configured .taskrc to have bumped into it?

**Comment by DCsunset** [comment]
Thanks for your feedback. It's because the environment variables were not set correctly inside the image. I've fixed it in the lastest version.
