### ISSUE TITLE
Use ordering of `task next`

### ISSUE THREAD

**Issue by rubdos** [DCsunset/taskwarrior-webui#6]
It would be nice if the default ordering would be equivalent with `task next`, the default ordering of the CLI tool itself.

I have a bunch of tasks without due date, and those seem to take priority over those *with* due date. I think `task next` uses the computed urgency, while this webui uses something... else?

**Comment by DCsunset** [comment]
It seems that there's something wrong with the build process.
I have fixed it now, and I may optimize the size in the future.
