### ISSUE TITLE
CA certificate not found - again

### ISSUE THREAD

**Issue by super-ben** [DCsunset/taskwarrior-webui#69]
Hello,

I know this was an issue before but I would rather reopen it, as after trying the WebUI after a few months I still encounter this issue:

```shell
docker logs taskwarrior-webui

> backend@1.0.0 start
> node ./dist/app.js

Server listening on http://0.0.0.0:3000
  <-- GET /tasks
TASKRC override: /.taskrc
TASKDATA override: /.task
Configuration override rc.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.json.depends.array=yes
Configuration override rc.bulk=0
  --> GET /tasks 200 145ms 383.27kb
  <-- POST /sync
TASKRC override: /.taskrc
TASKDATA override: /.task
Configuration override rc.confirmation=no
Configuration override rc.recurrence.confirmation=no
Configuration override rc.dependency.confirmation=no
Configuration override rc.json.depends.array=yes
Configuration override rc.bulk=0
CA certificate not found.
  xxx POST /sync 400 37ms -
```

I se up the container exactly as it is recommended, the only thing I changed is the port number for testing:

```shell
docker run -d -p 5678:80 --name taskwarrior-webui \
	-v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task \
	dcsunset/taskwarrior-webui
```

In the container, the volumes are mounted alright.

Any ideas what can cause this?

**Comment by DCsunset** [comment]
Issue #9 might be relevant.

The error may occur because the paths of the certificates are specified in your .taskrc. So it couldn't find it because the certificates locate in /.task rather than $HOME/.task.

A quick solution is to mount $HOME/.task to the same directory in the container (i.e. /home/username/.task).

**Comment by super-ben** [comment]
Thank you, I've already tried but with the same results. I'm out of ideas.

**Comment by DCsunset** [comment]
The problem still exists because you still haven't mounted it to $HOME dir **inside the container**. The correct way to do so is:

```sh
docker run -d -p 5678:80 --name taskwarrior-webui \
	-e TAKSRC=$HOME/.taskrc -e TASKDATA=$HOME/.task \
	-v $HOME/.taskrc:$HOME/.taskrc -v $HOME/.task:$HOME/.task \
	dcsunset/taskwarrior-webui
```

You can test whether the new command works. Since it's a commonly asked question, I will update the README once the issue is resolved.

**Comment by super-ben** [comment]
I've created this docker-compose (I use docker with that) file and now it works:

```shell
version: '3.8'
services:
  taskwarrior-webui:
    container_name: taskwarrior-webui
    image: dcsunset/taskwarrior-webui
    ports:
      - "5678:80"
    environment:
      - TASKRC=/home/username/.taskrc
      - TASKDATA=/home/username/.task
    volumes:
      - $HOME/.taskrc:/home/username/.taskrc
      - $HOME/.task:/home/username/.task
```
If I "translate" this to a standard docker command:
```shell
docker run -d -p 5678:80 --name taskwarrior-webui \
  -e TASKRC=/home/username/.taskrc \
  -e TASKDATA=/home/username/.task \
  -v $HOME/.taskrc:/home/username/.taskrc \
  -v $HOME/.task:/home/username/.task \
  dcsunset/taskwarrior-webui
```
Since this is something different (even the one you showed above) than the completely standard recommended command, I would recommend to update the README. :) I can confirm that it works now. Thanks for the assist!
