### ISSUE TITLE
Serve App via custom path

### ISSUE THREAD

**Issue by soerenschneider** [DCsunset/taskwarrior-webui#70]
Hi, great project!

I wanted to ask if it's possible to add a feature to run taskwarrior-webui behind a reverse proxy using a custom path (e.g. "/tasks" instead of "/").

Thanks!

**Comment by DCsunset** [comment]
I think it should probably work already with a reverse proxy. Have you tried it and encountered any issue?

**Comment by DCsunset** [comment]
Closing it due to inactivity

**Comment by dluciv** [comment]
@DCsunset No, it in fact does not, see https://github.com/DCsunset/taskwarrior-webui/issues/88#issuecomment-3016089321 please
