### ISSUE TITLE
Question: Can I create new tasks via the API without the frontend?

### ISSUE THREAD

**Issue by justinmartin** [DCsunset/taskwarrior-webui#76]
The frontend is beautiful and looks great on my phone, but I would like to use an iOS shortcut to create a task.  I can't work out if its possible to use the backend api to create a task without the frontend.

**Comment by DCsunset** [comment]
Yes, you can. You just need to send HTTP PUT request to the path `/tasks` at backend, where the body contains a list of tasks you want to create. You can check the backend routes for more info.

**Comment by justinmartin** [comment]
That is great.  It took a little more fiddling but I have it working.  Super thankful for your project.
