### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by kantoor** [DCsunset/taskwarrior-webui#81]
Is it possible to password protect this web interface? Must be missing the obvious here. Got it working fairly easy but it is now open for everyone that has the IP. Thank you for taking the time to answer this!

**Comment by DCsunset** [comment]
Authentication is not supported directly, but it is possible to use basic auth by configuring nginx (or you can even use your own reverse-proxy to do the auth).

For example, you can modify the file `nginx/server.conf` and mount it at `/etc/nginx/conf.d/default.conf`:
(you will also need you mount the `htpasswd` file at `/etc/htpasswd` in the example)

```conf
server {
    listen 80;
    listen [::]:80;

    # add auth
    auth_basic           "Protected page";
    auth_basic_user_file /etc/htpasswd;

    # remaining part unchanged
    ...
}
```

I will update the readme later as it's a common config.

**Comment by DCsunset** [comment]
Closing it as the the instructions have been added to README.
